cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'zsh'
brew 'zsh-completions'

brew 'coreutils'
brew 'openssl'
brew 'wget'

brew 'composer'
brew 'nvm'

cask 'amazon-music'
cask 'appcleaner'
cask 'arduino'
cask 'boxcryptor'
cask 'caffeine'
cask 'cocoapods'
cask 'docker'
cask 'dropbox'
cask 'evernote'
cask 'flux'
cask 'google-chrome'
cask 'intellij-idea'
cask 'istat-menus'
cask 'iterm2'
cask 'java'
cask 'kaleidoscope'
cask 'lastpass'
cask 'macdown'
cask 'mactex'
cask 'mendeley-desktop'
cask 'omnifocus'
cask 'omnigraffle'
cask 'owncloud'
cask 'phpstorm'
cask 'pycharm'
cask 'slack'
cask 'sourcetree'
cask 'steam'
cask 'steelseries-engine'
cask 'teamspeak-client'
cask 'vagrant'
cask 'virtualbox'
cask 'viscosity'
cask 'visual-studio-code'
cask 'vmware-fusion7'
cask 'webstorm'
cask 'yubikey-neo-manager'