#!/usr/bin/env bash

##
# Install Homebrew.
#
# @author   René Milzarek <rene.milzarek@gmail.com>
# @ref      Zach Holman (https://github.com/holman/dotfiles)  
# @license  MIT license (https://github.com/neotreat/dotfiles/blob/master/LICENSE.md)
##

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# Find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
